### ISSUE TITLE
Chore | Sync SSO layer from Ref Arch and test it

### ISSUE THREAD

**Issue by angelofenoglio** [binbashar/le-tf-infra-aws-template#30]
## Work to be done
- Make sure that the [template's sso layer](https://gitihub.com/binbashar/le-tf-infra-aws-template/tree/master/template/management/global/sso) is up to date with the [current sso implementation in the Ref Arch](https://github.com/binbashar/le-tf-infra-aws/tree/master/management/global/sso)
- Make sure that the service is in working order
- Update documentation accordingly

**Comment by exequielrafaela** [comment]
- https://github.com/binbashar/leverage/pull/184
- https://github.com/binbashar/le-ref-architecture-doc/pull/167
