### ISSUE TITLE
The template should support the symlinked common-variables.tf file

### ISSUE THREAD

**Issue by diego-ojeda-binbash** [binbashar/le-tf-infra-aws-template#31]
## Describe the Feature
New bootstrapped projects do not use the `config/common-variables.tf` file which is then symlinked by all layers to favor reusability of the variables defined in such file.

The feature is already implemented in the reference architecture so a reference can be borrowed from there:
- https://github.com/binbashar/le-tf-infra-aws/blob/master/config/common-variables.tf
- https://github.com/binbashar/le-tf-infra-aws/blob/master/apps-devstg/global/base-identities/common-variables.tf

**Comment by exequielrafaela** [comment]
@diego-ojeda-binbash OJ good catch! :) Thanks for creating this issue.
